spring.application.name=exploramocoa
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${DB_NAME:exploramocoa}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:valery27}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
